apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: springboot-test
  namespace: jenkins
spec:
  serviceName: "springboot-test"
  replicas: 2
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      imagePullSecrets:
        - name: $SECRET_NAME
      containers:
        - name: springboot
          image: $IMAGE_NAME
          ports:
            - containerPort: 8080
